/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author Lovish_Arora
 */
public class AddPostPanelDesign extends javax.swing.JPanel {

    /**
     * Creates new form AddPostPanelDesign
     */
    public AddPostPanelDesign() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jphoto = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        date_time = new javax.swing.JLabel();
        jdeletepost = new javax.swing.JButton();
        jaddstory = new javax.swing.JButton();
        jcaption = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 204, 204));
        setLayout(null);

        jphoto.setText("photo");
        add(jphoto);
        jphoto.setBounds(15, 6, 133, 131);

        jLabel2.setText("Caption");
        add(jLabel2);
        jLabel2.setBounds(6, 143, 60, 25);

        date_time.setText("date and time");
        add(date_time);
        date_time.setBounds(280, 6, 128, 29);

        jdeletepost.setText("Delete Post");
        add(jdeletepost);
        jdeletepost.setBounds(263, 49, 126, 38);

        jaddstory.setText("Add Story");
        add(jaddstory);
        jaddstory.setBounds(263, 103, 126, 43);
        add(jcaption);
        jcaption.setBounds(70, 140, 140, 40);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel date_time;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JButton jaddstory;
    public javax.swing.JLabel jcaption;
    public javax.swing.JButton jdeletepost;
    public javax.swing.JLabel jphoto;
    // End of variables declaration//GEN-END:variables
}
