/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author Lovish_Arora
 */
public class addstorypanel extends javax.swing.JPanel {

    /**
     * Creates new form addstorypanel
     */
    public addstorypanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jphoto = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jdeletestorybtn = new javax.swing.JButton();
        jcaption = new javax.swing.JLabel();

        setLayout(null);

        jphoto.setText("jLabel1");
        add(jphoto);
        jphoto.setBounds(37, 16, 200, 170);

        jLabel2.setText("caption");
        add(jLabel2);
        jLabel2.setBounds(280, 30, 70, 30);

        jdeletestorybtn.setText("DELETE STORY");
        add(jdeletestorybtn);
        jdeletestorybtn.setBounds(260, 130, 165, 39);

        jcaption.setText("jLabel1");
        add(jcaption);
        jcaption.setBounds(280, 70, 110, 40);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jcaption;
    public javax.swing.JButton jdeletestorybtn;
    public javax.swing.JLabel jphoto;
    // End of variables declaration//GEN-END:variables
}
