/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author Lovish_Arora
 */
public class PostUserPanelDesign extends javax.swing.JPanel {

    /**
     * Creates new form PostUserPanelDesign
     */
    public PostUserPanelDesign() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        date_time = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 255, 255));
        setForeground(new java.awt.Color(153, 255, 255));
        setLayout(null);

        jLabel1.setText("jLabel1");
        add(jLabel1);
        jLabel1.setBounds(30, 20, 110, 90);

        jLabel2.setText("Date And Time");
        add(jLabel2);
        jLabel2.setBounds(200, 40, 90, 30);

        jButton3.setText("Add Story");
        add(jButton3);
        jButton3.setBounds(290, 160, 160, 40);

        jButton4.setText("Delete Post");
        add(jButton4);
        jButton4.setBounds(290, 90, 160, 40);
        add(date_time);
        date_time.setBounds(330, 40, 90, 30);

        jLabel3.setText("Caption");
        add(jLabel3);
        jLabel3.setBounds(30, 170, 170, 50);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel date_time;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
