
import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.Unirest;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.File;
import java.net.URL;
import java.util.StringTokenizer;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Lovish_Arora
 */
public class UserEditFrame extends javax.swing.JFrame {

    /**
     * Creates new form UserEditFrame
     */
    File f;
    String user;

    public UserEditFrame(String username) {
        initComponents();
        Dimension d = new Dimension(Toolkit.getDefaultToolkit().getScreenSize());
        System.out.println(d);
        ImageIcon i1 = new ImageIcon("src/uploads/instapicbg.jpg");
//        Image img = i1.getImage().getScaledInstance(photolb.getWidth(), photolb.getHeight(), Image.SCALE_SMOOTH);
        Image img = i1.getImage().getScaledInstance(d.width, d.height, Image.SCALE_SMOOTH);
        photolb.setBounds(0, 0, d.width, d.height);
        ImageIcon i2 = new ImageIcon(img);
        photolb.setIcon(i2);

//        getContentPane().setBackground(Color.blue);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);

        setSize(600, 600);
        setVisible(true);
        user = username;
        jusername.setText(user);
        jusername.setEditable(false);
        getData();

    }

    void getData() {
        try {
            HttpResponse<String> res = Unirest.get("http://localhost:8999/getdata")
                    .queryString("username", user)
                    .asString();
            if (res.getStatus() == 200) {
                String ans = res.getBody();
                System.out.println("response is--->" + ans);
                if (ans.equals("FAILS")) {
                    JOptionPane.showMessageDialog(this, "no data found");
                } else {
                    StringTokenizer st = new StringTokenizer(ans, ";;");
                    String email = st.nextToken();
                    String phoneno = st.nextToken();
                    String photo = st.nextToken();
                    jemail.setText(email);
                    jphoneno.setText(phoneno);
                   // jphoto.setText(photo);
                    try {
                        URL url = new URL(Global.ipAddress + "GetResource/" + photo);
                        //System.out.println("Path of Image Stored in server side--------------" + url);
                        BufferedImage img = ImageIO.read(url);
                        Image resizedimage = img.getScaledInstance(jphoto.getWidth(), jphoto.getHeight(), Image.SCALE_SMOOTH);
                        jphoto.setIcon(new ImageIcon(resizedimage));

                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                }
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jbrowse = new javax.swing.JButton();
        jusername = new javax.swing.JTextField();
        jemail = new javax.swing.JTextField();
        jphoneno = new javax.swing.JTextField();
        jphoto = new javax.swing.JLabel();
        jeditprofile = new javax.swing.JButton();
        photolb = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("Edit Profile Here!");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(200, 20, 130, 50);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel2.setText("Username");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(120, 80, 90, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel3.setText("E-Mail");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(120, 120, 90, 30);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel4.setText("Phone number");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(120, 160, 100, 30);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel5.setText("Photo");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(120, 200, 90, 30);

        jbrowse.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jbrowse.setText("Browse");
        jbrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbrowseActionPerformed(evt);
            }
        });
        getContentPane().add(jbrowse);
        jbrowse.setBounds(110, 240, 90, 30);

        jusername.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        getContentPane().add(jusername);
        jusername.setBounds(240, 80, 150, 30);

        jemail.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        getContentPane().add(jemail);
        jemail.setBounds(240, 120, 150, 30);

        jphoneno.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        getContentPane().add(jphoneno);
        jphoneno.setBounds(240, 160, 150, 30);
        getContentPane().add(jphoto);
        jphoto.setBounds(250, 200, 140, 100);

        jeditprofile.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jeditprofile.setText("Edit Profile");
        jeditprofile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jeditprofileActionPerformed(evt);
            }
        });
        getContentPane().add(jeditprofile);
        jeditprofile.setBounds(180, 340, 140, 50);

        photolb.setText("jLabel6");
        getContentPane().add(photolb);
        photolb.setBounds(20, 40, 38, 16);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbrowseActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        int ans = chooser.showOpenDialog(this);
        if (ans == JFileChooser.APPROVE_OPTION) {
            f = chooser.getSelectedFile();
            
            ImageIcon icon = new ImageIcon(f.getPath());
            Image resizedImage = icon.getImage().getScaledInstance(jphoto.getWidth(), jphoto.getHeight(), Image.SCALE_AREA_AVERAGING);
            jphoto.setIcon(new ImageIcon(resizedImage));

        }

    }//GEN-LAST:event_jbrowseActionPerformed

    private void jeditprofileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jeditprofileActionPerformed
        // TODO add your handling code here:
        String email = jemail.getText();
        String phoneno = jphoneno.getText();

        if (email.isEmpty() || phoneno.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "All fieds are required.");

        } else if (email.indexOf("@") == -1) {
            JOptionPane.showMessageDialog(this, "Please enter a valid email address");
        } else if (phoneno.length() != 10) {
            JOptionPane.showMessageDialog(this, "Please enetr a valid phone number");
        } else if (f == null) {
            try {
                HttpResponse<String> res = Unirest.get(Global.ipAddress + "usereditwithoutphoto")
                        .queryString("username", user)
                        .queryString("email", email)
                        .queryString("phoneno", phoneno)
                        .asString();
                if (res.getStatus() == 200) {
                    String response = res.getBody();
                    if (response.equals("SUCCESS")) {
                        JOptionPane.showMessageDialog(this, "Edit profile successfully!");
                        getData();

                    } else {
                        JOptionPane.showMessageDialog(this, "Edit profile Fails! \n Invalid email or phone number\nPlease enter again");
                    }

                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        } else {
            try {
                HttpResponse<String> res = Unirest.post(Global.ipAddress + "usereditwithphoto")
                        .queryString("username", user)
                        .queryString("email", email)
                        .queryString("phoneno", phoneno)
                        .field("photo", f)
                        .asString();
                if (res.getStatus() == 200) {
                    String response = res.getBody();
                    if (response.equals("SUCCESS")) {
                        JOptionPane.showMessageDialog(this, "Edit profile successfully!");
                        getData();

                    } else {
                        JOptionPane.showMessageDialog(this, "Edit profile Fails! \n Invalid email or phone number\nPlease enter again");
                    }

                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }


    }//GEN-LAST:event_jeditprofileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserEditFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserEditFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserEditFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserEditFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserEditFrame("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton jbrowse;
    private javax.swing.JButton jeditprofile;
    private javax.swing.JTextField jemail;
    private javax.swing.JTextField jphoneno;
    private javax.swing.JLabel jphoto;
    private javax.swing.JTextField jusername;
    private javax.swing.JLabel photolb;
    // End of variables declaration//GEN-END:variables
}
