
import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.Unirest;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Lovish_Arora
 */
public class UserChangePasswordFrame extends javax.swing.JFrame {

    /**
     * Creates new form UserChangePasswordFrame
     */
    String user;

    public UserChangePasswordFrame(String username) {
        initComponents();
        
        Dimension d = new Dimension(Toolkit.getDefaultToolkit().getScreenSize());
        System.out.println(d);
        ImageIcon i1 = new ImageIcon("src/uploads/instapicbg.jpg");
//        Image img = i1.getImage().getScaledInstance(photolb.getWidth(), photolb.getHeight(), Image.SCALE_SMOOTH);
        Image img = i1.getImage().getScaledInstance(d.width, d.height, Image.SCALE_SMOOTH);
        photolb.setBounds(0, 0, d.width, d.height);
        ImageIcon i2 = new ImageIcon(img);
        photolb.setIcon(i2);

//        getContentPane().setBackground(Color.blue);
        setSize(d.width, d.height);
        setVisible(true);

        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    
        
        
        user = username;
        jusername.setText(user);
        jusername.setEditable(false);
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jusername = new javax.swing.JTextField();
        joldpass = new javax.swing.JPasswordField();
        jnewpass = new javax.swing.JPasswordField();
        jconfirmpass = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        photolb = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("Change Password Here!");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(200, 20, 170, 40);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel2.setText("Username");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(150, 80, 100, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel3.setText("Old Password");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(150, 120, 100, 30);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel4.setText("New Password");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(150, 160, 100, 30);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel5.setText("Confirm Password");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(150, 200, 120, 30);

        jusername.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        getContentPane().add(jusername);
        jusername.setBounds(290, 80, 150, 30);

        joldpass.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        joldpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                joldpassActionPerformed(evt);
            }
        });
        getContentPane().add(joldpass);
        joldpass.setBounds(290, 120, 150, 30);

        jnewpass.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jnewpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jnewpassActionPerformed(evt);
            }
        });
        getContentPane().add(jnewpass);
        jnewpass.setBounds(290, 160, 150, 30);

        jconfirmpass.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        getContentPane().add(jconfirmpass);
        jconfirmpass.setBounds(290, 200, 150, 30);

        jButton1.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jButton1.setText("Change Password");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(200, 260, 140, 40);

        photolb.setText("jLabel6");
        getContentPane().add(photolb);
        photolb.setBounds(10, 30, 38, 16);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jnewpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jnewpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jnewpassActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //get all data
        String username = jusername.getText();
        String oldpass = joldpass.getText();
        String newpass = jnewpass.getText();
        String confirmpass = jconfirmpass.getText();

        //check if empty
        //check if newpass and confirm pass are equal or not
        //send unirest get request
        //userchangepass wala resource
        if (oldpass.isEmpty() || newpass.isEmpty() || confirmpass.isEmpty()) {
            JOptionPane.showMessageDialog(this, "all Fields are reqiured");
        } else if (!newpass.equals(confirmpass)) {
            JOptionPane.showMessageDialog(this, "New password must match confirm password");
        } else {
            try {
                HttpResponse<String> res = Unirest.get("http://localhost:8999/userchangepassword")
                        .queryString("username", username)
                        .queryString("oldPassword", oldpass)
                        .queryString("newPassword", newpass)
                        .asString();
                if (res.getStatus() == 200) {
                    String response = res.getBody();
                    if (response.equals("SUCCESS")) {
                        JOptionPane.showMessageDialog(this, "Password Changed Sucessfull!");
                        dispose();
                        UserLoginFrame obj = new UserLoginFrame();

                    } else {
                        JOptionPane.showMessageDialog(this, "New password must match confirm passsword \n Please Enter again");
                    }

                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }        // TODO add your handling code here:

    }//GEN-LAST:event_jButton1ActionPerformed

    private void joldpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_joldpassActionPerformed


    }//GEN-LAST:event_joldpassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserChangePasswordFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserChangePasswordFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserChangePasswordFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserChangePasswordFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserChangePasswordFrame("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField jconfirmpass;
    private javax.swing.JPasswordField jnewpass;
    private javax.swing.JPasswordField joldpass;
    private javax.swing.JTextField jusername;
    private javax.swing.JLabel photolb;
    // End of variables declaration//GEN-END:variables
}
