/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Anchal
 */
public class userhomeposts extends javax.swing.JPanel {

    /**
     * Creates new form userhomeposts
     */
    public userhomeposts() {
        initComponents();
        setSize(400,250);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jusername = new javax.swing.JLabel();
        jlike = new javax.swing.JButton();
        jcount = new javax.swing.JLabel();
        jphoto = new javax.swing.JLabel();
        jcaption = new javax.swing.JLabel();

        setLayout(null);

        jusername.setText("username");
        add(jusername);
        jusername.setBounds(10, 140, 380, 30);

        jlike.setText("Like");
        jlike.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlikeActionPerformed(evt);
            }
        });
        add(jlike);
        jlike.setBounds(10, 210, 80, 22);

        jcount.setText("count");
        add(jcount);
        jcount.setBounds(100, 210, 50, 20);

        jphoto.setText("photo");
        add(jphoto);
        jphoto.setBounds(10, 10, 380, 110);

        jcaption.setText("caption");
        add(jcaption);
        jcaption.setBounds(10, 173, 370, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void jlikeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlikeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jlikeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel jcaption;
    public javax.swing.JLabel jcount;
    public javax.swing.JButton jlike;
    public javax.swing.JLabel jphoto;
    public javax.swing.JLabel jusername;
    // End of variables declaration//GEN-END:variables
}
