
import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.Unirest;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Lovish_Arora
 */
public class UserForgotPassword extends javax.swing.JFrame {

    /**
     * Creates new form UserForgotPassword
     */
    String username;
    String otp;

    public UserForgotPassword() {
        initComponents();
        Dimension d = new Dimension(Toolkit.getDefaultToolkit().getScreenSize());
        System.out.println(d);
        ImageIcon i1 = new ImageIcon("src/uploads/instapicbg.jpg");
//        Image img = i1.getImage().getScaledInstance(photolb.getWidth(), photolb.getHeight(), Image.SCALE_SMOOTH);
        Image img = i1.getImage().getScaledInstance(d.width, d.height, Image.SCALE_SMOOTH);
        photolb.setBounds(0, 0, d.width, d.height);
        ImageIcon i2 = new ImageIcon(img);
        photolb.setIcon(i2);

//        getContentPane().setBackground(Color.blue);
        setSize(d.width, d.height);

        jPanel1.setBounds(100, 100, 500, 200);
        jPanel2.setBounds(100, 100, 500, 200);
        jPanel3.setBounds(100, 100, 500, 200);
        jPanel2.setVisible(false);
        jPanel3.setVisible(false);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setTitle("Forgot Password");
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jusername = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jotp = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jnewpassword = new javax.swing.JPasswordField();
        jconfirmpassword = new javax.swing.JPasswordField();
        jButton3 = new javax.swing.JButton();
        photolb = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText(" FORGOT PASSWORD");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(280, 30, 250, 60);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel2.setText("Enter Username");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(200, 15, 130, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel3.setText("Username");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(100, 50, 100, 30);
        jPanel1.add(jusername);
        jusername.setBounds(250, 50, 170, 30);

        jButton1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jButton1.setText("Generate OTP");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(170, 130, 200, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(120, 140, 500, 200);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel2.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel4.setText("OTP Verification");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(200, 15, 130, 30);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel5.setText("Enter OTP");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(100, 50, 100, 30);
        jPanel2.add(jotp);
        jotp.setBounds(250, 50, 170, 30);

        jButton2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jButton2.setText("Proceed");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(170, 130, 200, 40);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(120, 380, 500, 200);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel3.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel6.setText("Set New Password");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(200, 15, 130, 30);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel7.setText("Enter New Password");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(50, 50, 170, 30);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel8.setText("Enter Confirm Password");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(50, 100, 170, 30);
        jPanel3.add(jnewpassword);
        jnewpassword.setBounds(250, 50, 170, 30);
        jPanel3.add(jconfirmpassword);
        jconfirmpassword.setBounds(250, 100, 170, 30);

        jButton3.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jButton3.setText("Submit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3);
        jButton3.setBounds(170, 150, 200, 40);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(120, 620, 500, 200);

        photolb.setText("jLabel9");
        getContentPane().add(photolb);
        photolb.setBounds(20, 20, 38, 16);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

         username = jusername.getText();
        if (username.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Username field is empty");
        } else {
            try {
                HttpResponse<String> res = Unirest.get("http://localhost:8999/userforgotpassword")
                        .queryString("username", username)
                        .asString();
                if (res.getStatus() == 200) {
                    String ans = res.getBody();

                    if (ans.equals("FAILS")) {
                        JOptionPane.showMessageDialog(rootPane, "Please enter a valid username");
                    } else {
                        otp = ans;
                        JOptionPane.showMessageDialog(rootPane, "OTP is " + otp);
                        jPanel1.setVisible(false);
                        jPanel2.setVisible(true);

                    }
                }

            } catch (Exception e) {
                e.printStackTrace();
            }

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String otpfield = jotp.getText();
        if (otp.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "OTP field is empty");
        } else {
            try {
                if (otpfield.equals(otp)) {
                    jPanel2.setVisible(false);
                    jPanel3.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Please enter correct OTP");
                }

            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String newpassword = jnewpassword.getText();
        String confirmpassword = jconfirmpassword.getText();
        if (newpassword.equals("") || confirmpassword.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "New Password & Confirm Password field is empty");
        } else {
            if (newpassword.equals(confirmpassword)) {
                try {
                    HttpResponse<String> res = Unirest.get("http://localhost:8999/usersetpassword")
                            .queryString("username", username)
                            .queryString("newpassword", newpassword)
                            .asString();

                    if (res.getStatus() == 200) {
                        String ans = res.getBody();
                        
                        if (ans.equals("UPDATED")) {
                            JOptionPane.showMessageDialog(rootPane, "Password Updated");
                            dispose();
                            UserLoginFrame obj =new UserLoginFrame();
                        } else {
                            JOptionPane.showMessageDialog(rootPane,"Something went wrong /n Error Occured");
                        }
                        
                    }
                    else{
                    JOptionPane.showMessageDialog(rootPane,"New Password & Confirm Password must be same");
                    }

                } catch (Exception e) {
                    e.printStackTrace();
                }
            }

        }

    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserForgotPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jconfirmpassword;
    private javax.swing.JPasswordField jnewpassword;
    private javax.swing.JTextField jotp;
    private javax.swing.JTextField jusername;
    private javax.swing.JLabel photolb;
    // End of variables declaration//GEN-END:variables
}
