/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author Lovish_Arora
 */
public class UserMyFollowingPanelDesign extends javax.swing.JPanel {

    /**
     * Creates new form UserMyFollowingPanelDesign
     */
    public UserMyFollowingPanelDesign() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jphoto = new javax.swing.JLabel();
        jusername = new javax.swing.JLabel();
        jemail = new javax.swing.JLabel();
        jfollowing = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 204));
        setLayout(null);

        jphoto.setText("jLabel2");
        add(jphoto);
        jphoto.setBounds(20, 10, 100, 100);

        jusername.setText("jLabel3");
        add(jusername);
        jusername.setBounds(140, 10, 150, 40);

        jemail.setText("jLabel4");
        add(jemail);
        jemail.setBounds(140, 60, 150, 40);

        jfollowing.setText("Following");
        add(jfollowing);
        jfollowing.setBounds(320, 30, 130, 50);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel jemail;
    public javax.swing.JButton jfollowing;
    public javax.swing.JLabel jphoto;
    public javax.swing.JLabel jusername;
    // End of variables declaration//GEN-END:variables
}
