
import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.Unirest;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.net.URL;
import java.util.StringTokenizer;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Lovish_Arora
 */
public class UserAddStory extends javax.swing.JFrame {

    /**
     * Creates new form UserAddStory
     */
    File f;
    String postid;
    BufferedImage img, changedimg;
    Image resizedImage;
    JFileChooser chooser = new JFileChooser();

    public UserAddStory(String postid) {
        initComponents();
        this.postid = postid;
        System.out.println("postid--in add story----->" + postid);
        Dimension d = new Dimension(Toolkit.getDefaultToolkit().getScreenSize());
        System.out.println(d);
        ImageIcon i1 = new ImageIcon("src/uploads/instapicbg.jpg");
//        Image img = i1.getImage().getScaledInstance(photolb.getWidth(), photolb.getHeight(), Image.SCALE_SMOOTH);
        Image img = i1.getImage().getScaledInstance(d.width, d.height, Image.SCALE_SMOOTH);
        photolb.setBounds(0, 0, d.width, d.height);
        ImageIcon i2 = new ImageIcon(img);
        photolb.setIcon(i2);
        setSize(d.width, d.height);
        setVisible(true);
        getAllStories(postid);
        //user = username;

        setDefaultCloseOperation(DISPOSE_ON_CLOSE);

    }

//    UserAddStory() {
//        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        captiontextarea = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jphoto = new javax.swing.JLabel();
        jstory = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        mainpanel = new javax.swing.JPanel();
        jblur = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jbrighter = new javax.swing.JButton();
        jdarker = new javax.swing.JButton();
        jgrayscale = new javax.swing.JButton();
        jhefe = new javax.swing.JButton();
        jlofi = new javax.swing.JButton();
        jnashville = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        photolb = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("Add Story Here!!");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(450, 30, 397, 69);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel2.setText("Caption");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(160, 170, 80, 50);

        captiontextarea.setColumns(20);
        captiontextarea.setRows(5);
        jScrollPane1.setViewportView(captiontextarea);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(300, 170, 250, 86);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel3.setText("Photo");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(160, 340, 120, 40);

        jButton1.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jButton1.setText("Browse");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(150, 420, 100, 40);
        getContentPane().add(jphoto);
        jphoto.setBounds(300, 310, 250, 180);

        jstory.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jstory.setText("Add Story");
        jstory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jstoryActionPerformed(evt);
            }
        });
        getContentPane().add(jstory);
        jstory.setBounds(600, 640, 370, 40);

        mainpanel.setBackground(new java.awt.Color(102, 255, 255));
        mainpanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        mainpanel.setLayout(null);
        jScrollPane2.setViewportView(mainpanel);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(610, 170, 390, 450);

        jblur.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jblur.setForeground(new java.awt.Color(255, 0, 0));
        jblur.setText("Blur ");
        jblur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jblurActionPerformed(evt);
            }
        });
        getContentPane().add(jblur);
        jblur.setBounds(190, 510, 100, 30);

        jButton3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jButton3.setText("Save Changes");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(190, 630, 150, 40);

        jbrighter.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jbrighter.setForeground(new java.awt.Color(255, 0, 0));
        jbrighter.setText("Brighter");
        jbrighter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbrighterActionPerformed(evt);
            }
        });
        getContentPane().add(jbrighter);
        jbrighter.setBounds(330, 510, 100, 30);

        jdarker.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jdarker.setForeground(new java.awt.Color(255, 0, 0));
        jdarker.setText("Darker ");
        jdarker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdarkerActionPerformed(evt);
            }
        });
        getContentPane().add(jdarker);
        jdarker.setBounds(470, 510, 100, 30);

        jgrayscale.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jgrayscale.setForeground(new java.awt.Color(255, 0, 0));
        jgrayscale.setText("Gray Scale ");
        jgrayscale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jgrayscaleActionPerformed(evt);
            }
        });
        getContentPane().add(jgrayscale);
        jgrayscale.setBounds(190, 550, 100, 30);

        jhefe.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jhefe.setForeground(new java.awt.Color(255, 0, 0));
        jhefe.setText("Hefe ");
        jhefe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jhefeActionPerformed(evt);
            }
        });
        getContentPane().add(jhefe);
        jhefe.setBounds(330, 550, 100, 30);

        jlofi.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jlofi.setForeground(new java.awt.Color(255, 0, 0));
        jlofi.setText("LoFi");
        jlofi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlofiActionPerformed(evt);
            }
        });
        getContentPane().add(jlofi);
        jlofi.setBounds(470, 550, 100, 30);

        jnashville.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jnashville.setForeground(new java.awt.Color(255, 0, 0));
        jnashville.setText("Nashville");
        jnashville.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jnashvilleActionPerformed(evt);
            }
        });
        getContentPane().add(jnashville);
        jnashville.setBounds(190, 590, 100, 30);

        jButton12.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jButton12.setForeground(new java.awt.Color(255, 0, 0));
        jButton12.setText("No Filter");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton12);
        jButton12.setBounds(470, 590, 100, 30);

        jButton13.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jButton13.setForeground(new java.awt.Color(255, 0, 0));
        jButton13.setText("Walden");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton13);
        jButton13.setBounds(330, 590, 100, 30);

        photolb.setText("jLabel4");
        getContentPane().add(photolb);
        photolb.setBounds(60, 20, 38, 16);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int ans = chooser.showOpenDialog(this);
        if (ans == JFileChooser.APPROVE_OPTION) {
            f = chooser.getSelectedFile();
            try {
                //-------- step2
                img = ImageIO.read(f);
            } catch (IOException ex) {
                ex.printStackTrace();
            }
            ImageIcon icon = new ImageIcon(f.getPath());
            Image resizedImage = icon.getImage().getScaledInstance(jphoto.getWidth(), jphoto.getHeight(), Image.SCALE_AREA_AVERAGING);
            jphoto.setIcon(new ImageIcon(resizedImage));

        }        // TODO add your handling code here:

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jstoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jstoryActionPerformed
        // TODO add your handling code here:
        String caption = captiontextarea.getText();

        if (f == null) {
            JOptionPane.showMessageDialog(this, "Please select a photo");
        } else if (caption.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter caption");

        } else {
            try {

                HttpResponse<String> res = Unirest.post("http://localhost:8999/useraddstory")
                        .queryString("caption", caption)
                        .queryString("postid", postid)
                        .field("photo", f)
                        .asString();
                if (res.getStatus() == 200) {
                    String response = res.getBody();
                    System.out.println("Response---->" + response);
                    if (response.equals("SUCCESS")) {
                        JOptionPane.showMessageDialog(this, "Story added successfully");
                        getAllStories(postid);
                    } else {
                        JOptionPane.showMessageDialog(this, "Add Story failed");

                    }

                }
            } catch (Exception e) {
                e.printStackTrace();

            }
        }
    }//GEN-LAST:event_jstoryActionPerformed

    private void jblurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jblurActionPerformed
        new Thread(new Runnable() {
            public void run() {
                BlurFilter obj = new BlurFilter();
                BufferedImage grayimg = obj.filter(img);
                resizedImage = grayimg.getScaledInstance(jphoto.getWidth(), jphoto.getHeight(), Image.SCALE_SMOOTH);
                changedimg = imageToBufferedImage(resizedImage);
                jphoto.setIcon(new ImageIcon(changedimg));
                repaint();
            }
        }).start();        // TODO add your handling code here:
    }//GEN-LAST:event_jblurActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int ans = chooser.showSaveDialog(this);
        if (ans == JFileChooser.APPROVE_OPTION) {
            f = chooser.getSelectedFile();
            try {
                ImageIO.write(changedimg, "jpg", f);
                JOptionPane.showMessageDialog(this, "File saved successfully !");
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jbrighterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbrighterActionPerformed
        new Thread(new Runnable() {
            public void run() {
                BrighterFilter obj = new BrighterFilter();
                BufferedImage grayimg = obj.filter(img);
                resizedImage = grayimg.getScaledInstance(jphoto.getWidth(), jphoto.getHeight(), Image.SCALE_SMOOTH);
                changedimg = imageToBufferedImage(resizedImage);
                jphoto.setIcon(new ImageIcon(changedimg));
                repaint();
            }
        }).start();          // TODO add your handling code here:
    }//GEN-LAST:event_jbrighterActionPerformed

    private void jdarkerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdarkerActionPerformed
        new Thread(new Runnable() {
            public void run() {
                DarkerFilter obj = new DarkerFilter();
                BufferedImage grayimg = obj.filter(img);
                resizedImage = grayimg.getScaledInstance(jphoto.getWidth(), jphoto.getHeight(), Image.SCALE_SMOOTH);
                changedimg = imageToBufferedImage(resizedImage);
                jphoto.setIcon(new ImageIcon(changedimg));
                repaint();
            }
        }).start();          // TODO add your handling code here:
    }//GEN-LAST:event_jdarkerActionPerformed

    private void jgrayscaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jgrayscaleActionPerformed
        new Thread(new Runnable() {
            public void run() {
                GrayscaleFilter obj = new GrayscaleFilter();
                BufferedImage grayimg = obj.filter(img);
                resizedImage = grayimg.getScaledInstance(jphoto.getWidth(), jphoto.getHeight(), Image.SCALE_SMOOTH);
                changedimg = imageToBufferedImage(resizedImage);
                jphoto.setIcon(new ImageIcon(changedimg));
                repaint();
            }
        }).start();        // TODO add your handling code here:
    }//GEN-LAST:event_jgrayscaleActionPerformed

    private void jhefeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jhefeActionPerformed
        new Thread(new Runnable() {
            public void run() {
                HefeFilter obj = new HefeFilter();
                BufferedImage grayimg = obj.filter(img);
                resizedImage = grayimg.getScaledInstance(jphoto.getWidth(), jphoto.getHeight(), Image.SCALE_SMOOTH);
                changedimg = imageToBufferedImage(resizedImage);
                jphoto.setIcon(new ImageIcon(changedimg));
                repaint();
            }
        }).start();          // TODO add your handling code here:
    }//GEN-LAST:event_jhefeActionPerformed

    private void jlofiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlofiActionPerformed
        new Thread(new Runnable() {
            public void run() {
                LoFiFilter obj = new LoFiFilter();
                BufferedImage grayimg = obj.filter(img);
                resizedImage = grayimg.getScaledInstance(jphoto.getWidth(), jphoto.getHeight(), Image.SCALE_SMOOTH);
                changedimg = imageToBufferedImage(resizedImage);
                jphoto.setIcon(new ImageIcon(changedimg));
                repaint();
            }
        }).start();          // TODO add your handling code here:
    }//GEN-LAST:event_jlofiActionPerformed

    private void jnashvilleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jnashvilleActionPerformed
        new Thread(new Runnable() {
            public void run() {
                NashvilleFilter obj = new NashvilleFilter();
                BufferedImage grayimg = obj.filter(img);
                resizedImage = grayimg.getScaledInstance(jphoto.getWidth(), jphoto.getHeight(), Image.SCALE_SMOOTH);
                changedimg = imageToBufferedImage(resizedImage);
                jphoto.setIcon(new ImageIcon(changedimg));
                repaint();
            }
        }).start();          // TODO add your handling code here:
    }//GEN-LAST:event_jnashvilleActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        new Thread(new Runnable() {
            public void run() {
                NoFilter obj = new NoFilter();
                BufferedImage grayimg = obj.filter(img);
                resizedImage = grayimg.getScaledInstance(jphoto.getWidth(), jphoto.getHeight(), Image.SCALE_SMOOTH);
                changedimg = imageToBufferedImage(resizedImage);
                jphoto.setIcon(new ImageIcon(changedimg));
                repaint();
            }
        }).start();          // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        new Thread(new Runnable() {
            public void run() {
                WaldenFilter obj = new WaldenFilter();
                BufferedImage grayimg = obj.filter(img);
                resizedImage = grayimg.getScaledInstance(jphoto.getWidth(), jphoto.getHeight(), Image.SCALE_SMOOTH);
                changedimg = imageToBufferedImage(resizedImage);
                jphoto.setIcon(new ImageIcon(changedimg));
                repaint();
            }
        }).start();          // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed
    public static BufferedImage imageToBufferedImage(Image img) {
        BufferedImage bi = new BufferedImage(img.getWidth(null), img.getHeight(null), BufferedImage.TYPE_INT_RGB);
        Graphics bg = bi.getGraphics();
        bg.drawImage(img, 0, 0, null);
        bg.dispose();
        return bi;
    }

    public void getAllStories(String postid) {
        try {
            HttpResponse<String> res = Unirest.get("http://localhost:8999/getallstories")
                    .queryString("postid", postid)
                    .asString();
            //-----//server working correctly
            if (res.getStatus() == 200) {
                String response = res.getBody();
                System.out.println("Response---->" + response);
                if (response.equals("SUCCESS")) {
                    JOptionPane.showMessageDialog(this, " added successfully");

                } else {
                    System.out.println("Response is---->" + response);
                    StringTokenizer st = new StringTokenizer(response, "~~");
                    int count = st.countTokens();
                    //int obj[]=new int[count];
                    mainpanel.setPreferredSize(new Dimension(400, count * 350));
                    addstorypanel obj[] = new addstorypanel[count];
                    int x = 10, y = 10;
                    mainpanel.removeAll();
                    for (int i = 0; i < count; i++) {
                        String userInfo = st.nextToken();
                        StringTokenizer st2 = new StringTokenizer(userInfo, "!!");
                        String caption = st2.nextToken();
                        String photo = st2.nextToken();
                        int storyid = Integer.parseInt(st2.nextToken());
                        System.out.println("caption-----" + caption);
                        System.out.println("photo-----" + photo);
                        //System.out.println("postid-----" + postid);
                        obj[i] = new addstorypanel();
                        obj[i].jphoto.setText(photo);
                        obj[i].jcaption.setText(caption);
                        try {
                            URL url = new URL(Global.ipAddress + "GetResource/" + photo);
                            //System.out.println("Path of Image Stored in server side--------------" + url);
                            BufferedImage img = ImageIO.read(url);
                            Image resizedimage = img.getScaledInstance(obj[i].jphoto.getWidth(), obj[i].jphoto.getHeight(), Image.SCALE_SMOOTH);
                            obj[i].jphoto.setIcon(new ImageIcon(resizedimage));

                        } catch (Exception e) {
                            e.printStackTrace();
                        }
                        //when follow button is clicked/
                        obj[i].jdeletestorybtn.addActionListener(new ActionListener() {
                            @Override
                            public void actionPerformed(ActionEvent e) {

                                //code pending request
                                getAllStories(postid);
                                // useraddstory obj = new useraddstory(postid);
                            }
                        });
                        obj[i].setBounds(x, y, 400, 250);
                        mainpanel.add(obj[i]);
                        y += 350;
                    }
                    mainpanel.repaint();
                }

            }
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserAddStory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserAddStory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserAddStory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserAddStory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserAddStory("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea captiontextarea;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jblur;
    private javax.swing.JButton jbrighter;
    private javax.swing.JButton jdarker;
    private javax.swing.JButton jgrayscale;
    private javax.swing.JButton jhefe;
    private javax.swing.JButton jlofi;
    private javax.swing.JButton jnashville;
    private javax.swing.JLabel jphoto;
    private javax.swing.JButton jstory;
    private javax.swing.JPanel mainpanel;
    private javax.swing.JLabel photolb;
    // End of variables declaration//GEN-END:variables
}
